### ISSUE TITLE
How to send file by curl

### ISSUE THREAD

**Issue by yaohailei** [hellojukay/httpfs#3]
Hello:
    Due to certain reasons, the browser cannot be used and curl must be used.Can you tell me how to use it, thank you!

**Comment by hellojukay** [comment]
@yaohailei If your server directory  is `http://ip:port/folder1/` , and you are going to upload file `example.txt` to the server , you can use the blow command:
```
curl -i -X POST -H "Content-Type: multipart/form-data" -F  "file=@example.txt" -F "name=example.txt" http://ip:port/folder1/
```

**Comment by hellojukay** [comment]
For httpfs version 0.5.0 you can upload file with curl 
```
curl -T filename https://localhost:8100/directory
```
