### ISSUE TITLE
文件上传到指定目录如何指定

### ISSUE THREAD

**Issue by 786262170** [hellojukay/httpfs#4]
当服务端口8100启动后，默认server地址是localhost:8100, 如果我想上传一个zip文件到指定目录

request url该如何指定呢？？

**Comment by hellojukay** [comment]
@786262170 你好，在启动 httpfs 程序的可以指定目录（后面的所有文件读写都是基于这个大的目录)
```
Usage of ./httpfs:
  -open
    	open with default browser
  -p int
    	port to serve on (default 8100)
  -path string
    	the directory of static file to host (default "./")
  -version
    	print program version
```
假设我们指定的 path 是 /tmp 目录，如果我们要把 work.txt 这个 文件上传到 /tmp/aaa/bbb/ccc 目录(目录如果不存在会自动创建),我们可以使用 curl 命令
```
curl -i -X POST -H "Content-Type: multipart/form-data" -F  "file=@work.txt" -F "name=work.txt" http://127.0.0.1:8100/aaa/bbb/ccc/
```

**Comment by 786262170** [comment]
我的请求信息
curl --location --request POST 'http://127.0.0.1:8100/file/upload/acheck/test/product-operation/003007012_20240620200000/' \
--form 'file=@"/D:/storage/product-operation1.zip"' \
--form 'name="product-operation1.zip"'

httpfs服务端日志：
25 12:04:43 upload file filename=product-operation1.zip error, create file failed open storage/file/upload/acheck/test/product-operation/003007012_20240620200000/product-operation1.zip: The system cannot find the path specified.


我是用的windows终端，似乎是不可行的。

**Comment by hellojukay** [comment]
@786262170 需要安装最新版本(0.4.0)，这个功能是昨天才加上的
```bash
go install github.com/hellojukay/httpfs@latest
```
或者自己用最新代码编译一份，

**Comment by hellojukay** [comment]
@786262170 最新版 0.5.0 上传文件的方式更加简单
```
curl -T filename http://localhost:8100/directory/
```

**Comment by 786262170** [comment]
感谢！
